//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemonArtAcademy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class courseTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public courseTable()
        {
            this.teachingLoads = new HashSet<teachingLoad>();
        }
    
        public string courseId { get; set; }
        public string courseName { get; set; }
        public Nullable<int> credits { get; set; }
        public Nullable<int> department { get; set; }
    
        public virtual departmentTable departmentTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teachingLoad> teachingLoads { get; set; }
    }
}
