//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemonArtAcademy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class departmentTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public departmentTable()
        {
            this.courseTables = new HashSet<courseTable>();
        }
    
        public int depId { get; set; }
        public string depName { get; set; }
        public Nullable<int> faculty { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<courseTable> courseTables { get; set; }
        public virtual facultyTable facultyTable { get; set; }
    }
}
