//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemonArtAcademy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class lecturerTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public lecturerTable()
        {
            this.teachingLoads = new HashSet<teachingLoad>();
        }
    
        public string lecturerId { get; set; }
        public string fullName { get; set; }
        public string lecturerAddress { get; set; }
        public string lecturerGender { get; set; }
        public string lecturerPhone { get; set; }
        public string lecturerEmail { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<teachingLoad> teachingLoads { get; set; }
    }
}
