//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DemonArtAcademy.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class teachingLoad
    {
        public int Id { get; set; }
        public string course { get; set; }
        public string lecturer { get; set; }
    
        public virtual courseTable courseTable { get; set; }
        public virtual lecturerTable lecturerTable { get; set; }
    }
}
